apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: authority-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: ssh://git@github.com/sauveergoel/blockchain-automation-framework.git
    ref: indytest
  values:
    metadata:
      name: authority-dtg
      namespace: authority-ns
    organization:
      name: authority
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"XPWEydyNqYEQJ8miVWxmcy","role":"0","verkey":"HZdEPmviNCGVB8LGpdj16D3c7nGG8saazJaDp1qCGkNJ"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-trustee","dest":"3q8Jt54s2zQBnm4C9ZSVCH","role":"0","verkey":"2YTM6sAecqf941QJSmAhbfiK5Ni7QHjhFcYNk9cPhuPK"},"metadata":{"from":"XPWEydyNqYEQJ8miVWxmcy"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-1","dest":"7RRbWHGyPxXbxXNG4Kvc8c","role":"2","verkey":"4Vz4PX79EgVzdbUuYZXVXgJHoNee8mYrFAuH4pAt3sbn"},"metadata":{"from":"3q8Jt54s2zQBnm4C9ZSVCH"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-2","dest":"6eTUuuW6ag69rVuQKY8p1H","role":"2","verkey":"45UYmsZEpeVomY51BHeqEfVh8PHcZz9x1FfqqAKNWQEt"},"metadata":{"from":"3q8Jt54s2zQBnm4C9ZSVCH"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-trustee","dest":"K3Ypop7CHWqmeLcyg9vYnm","role":"0","verkey":"AqQU7FH4j646RyXH1uryvgrAEfpbbtKkGjiaQhG2eQgN"},"metadata":{"from":"XPWEydyNqYEQJ8miVWxmcy"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-1","dest":"3jJe4abGJVYBd4Snjjsrfa","role":"2","verkey":"2VHJi8io23ezeyzkYB9uUSjqPUAEazWSM57VEFXDhR65"},"metadata":{"from":"K3Ypop7CHWqmeLcyg9vYnm"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-2","dest":"ASjXA4Vp66QdRGyfpdNCvF","role":"2","verkey":"69XvYWDt46YfWZFUu1ym2ii3jed2gjGSoB6Y35cRcE4U"},"metadata":{"from":"K3Ypop7CHWqmeLcyg9vYnm"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
